name: Update Tag

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest
    inputs:
      tag-name:
        description: 'Name of the tag to be updated'
        required: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create tag
        id: create_tag
        run: |
          git tag -f ${{ inputs.tag-name }} main
          git push -f origin ${{ inputs.tag-name }}
