name: Update Tag

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create tag
        run: |
          git tag -f $TAG_NAME main
          git push -f origin $TAG_NAME
